eureka:
  client:
    region: region1
    serviceUrl:
      zone1: http://user:password@localhost:8761/eureka/
      zone2: http://user:password@127.0.0.1:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
